//-*-c-*-
//=============================================================================
//
// Copyright (c) Ant Group Co., Ltd
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//=============================================================================

// This file should be auto generated by onnx2c.py,
// it's used as driver for testing ONNX.

#include <math.h>

#include "common/rtlib.h"

double Expected_data[] = {0.055279694, -0.0118674375, -0.0066833645, -0.14045909, -0.026491726, -0.079734296, 0.025135407, -0.08075381, 0.042529836, 0.13177998};
int Expected_len = 10;

/**
* @brief generate input data for testing ONNX
*
*
* @param n
* @param c
* @param h
* @param w
* @param data, data pointer
* @return TENSOR input data
*/
TENSOR *Generate_input_data(size_t n, size_t c, size_t h, size_t w, double *data) {
    return Alloc_tensor(n, c, h, w, data);
}

/**
 * @brief validate output vector with expect vector
 *
 *
 * @param result double *
 * @param expect double *
 * @param len int
 * @return return true if value match
 */
bool Validate_output_data_absolute_error(double *result, double *expect, int len) {
  bool print_all = false;
  const char* print_all_str = getenv("PRINT_ALL");
  if(print_all_str != NULL) {
    printf("Value of PRINT_ALL: %s\n", print_all_str);
    print_all = true;
  }

  const char* absolute_error_str = getenv("ABS_ERROR");
  double absolute_error = 0.0001;
  if(absolute_error_str != NULL) {
    printf("Value of ABS_ERROR: %s\n", absolute_error_str);
    absolute_error = atof(absolute_error_str);
  }
  printf("expect absolute error less than: %f\n", absolute_error);
  int count = 0;
  for(int i = 0; i < len; i++) {
    double result_absolute_error = fabs(result[i] - expect[i]);
    if(print_all) {
      printf("index: %d, result: %f, expect: %f, result absolute error=%f, ", i, result[i], expect[i], result_absolute_error);
      if(result_absolute_error > absolute_error) {
        count++;
        printf("%d failed\n", count);
      } else {
        printf("ok\n");
      }
    } else {
      if(result_absolute_error > absolute_error) {
        printf("index: %d, value: %f != %f, result absolute error=%f\n", i, result[i], expect[i], result_absolute_error);
        return false;
      }
    }
  }
  if(print_all && (count != 0)) {
    return false;
  }
  return true;
}

bool Validate_output_data_relative_error(double *result, double *expect, int len) {
  bool print_all = false;
  const char* print_all_str = getenv("PRINT_ALL");
  if(print_all_str != NULL) {
    printf("Value of PRINT_ALL: %s\n", print_all_str);
    print_all = true;
  }

  const char* relative_error_str = getenv("REL_ERROR");
  double relative_error = 0.001;
  if(relative_error_str != NULL) {
    printf("Value of REL_ERROR: %s\n", relative_error_str);
    relative_error = atof(relative_error_str);
  }
  printf("expect relative error less than: %f\n", relative_error);
  int count = 0;
  for(int i = 0; i < len; i++) {
    double result_relative_error = fabs(result[i] - expect[i])/expect[i];
    if(print_all) {
      printf("index: %d, result: %f, expect: %f, result relative error=%f, ", i, result[i], expect[i], result_relative_error);
      if(result_relative_error > relative_error) {
        count++;
        printf("%d failed\n", count);
      } else {
        printf("ok\n");
      }
    } else {
      if (result_relative_error > relative_error) {
        printf("index: %d, value: %f != %f, result relative error: %f\n", i, result[i], expect[i], result_relative_error);
        return false;
      }
    }
  }
  if(print_all && (count != 0)) {
    return false;
  }
  return true;
}

int main(int argc, char* argv[]) {
  Prepare_context();

  double input1[]={-0.024126194417476654, -0.017732128500938416, -0.06731325387954712, -0.007497668266296387, -0.02877037227153778, 0.08807376772165298, 0.05638007074594498, 0.03481484204530716, -0.075764499604702, 0.057768918573856354, -0.05348609760403633, -0.054547883570194244, 0.05016949027776718, -0.0605330727994442, 0.07902649790048599, -0.09537225216627121, -0.07728620618581772, -0.07696700096130371, -0.02297399193048477, -0.08364810049533844, -0.009176753461360931, -0.09589860588312149, 0.07210997492074966, -0.0433267243206501, 0.06949528306722641, 0.03141512721776962, 0.021480001509189606, 0.07775700837373734, 0.029268287122249603, -0.07969162613153458, 0.0043406859040260315, -0.06455470621585846, 0.012299463152885437, 0.012439742684364319, 0.08351659029722214, 0.0875842347741127, -0.013908222317695618, -0.0173235684633255, 0.09319119900465012, 0.08043818920850754, -0.07994890213012695, -0.012273862957954407, 0.055702827870845795, 0.03259044140577316, 0.050027035176754, -0.010353483259677887, -0.07279971987009048, 0.046869538724422455, -0.08868477493524551, -0.06215761974453926, -0.027067109942436218, 0.03194848448038101, 0.047162123024463654, -0.09227265417575836, -0.07309465110301971, -0.09394168853759766, 0.061076484620571136, -0.06386406719684601, 0.06927225738763809, 0.07005134969949722, -0.07542560249567032, -0.008897088468074799, 0.02954990416765213, -0.08601291477680206};
  TENSOR *input_data1 = Generate_input_data(1, 1, 1, 64, input1);
  printf("input");
  Print_tensor(stdout, input_data1);
  Prepare_input(input_data1, "input");
  Free_tensor(input_data1);

  Run_main_graph();

  double  *result = Handle_output("output");

  Finalize_context();

  return 0;
}
