//-*-c-*-
//=============================================================================
//
// Copyright (c) Ant Group Co., Ltd
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//=============================================================================

#ifndef RTLIB_RT_ACE_ACE_API_H
#define RTLIB_RT_ACE_ACE_API_H

//! @brief ace_api.h
//! Define Ace API can be used by rtlib

#if __has_include(<ace/he_engine/Context.h>)
#define RT_ACE_HAS_CONTEXT 1
#else
#define RT_ACE_HAS_CONTEXT 0
#endif
#if __has_include(<ace/he_engine/Evaluator.h>)
#define RT_ACE_HAS_EVALUATOR 1
#else
#define RT_ACE_HAS_EVALUATOR 0
#endif
#if __has_include(<ace/he_engine/Ciphertext.h>)
#define RT_ACE_HAS_CIPHERTEXT 1
#else
#define RT_ACE_HAS_CIPHERTEXT 0
#endif
#if __has_include(<ace/he_engine/Plaintext.h>)
#define RT_ACE_HAS_PLAINTEXT 1
#else
#define RT_ACE_HAS_PLAINTEXT 0
#endif
#if __has_include(<rmm/cuda_stream_pool.hpp>)
#define RT_ACE_HAS_RMM 1
#else
#define RT_ACE_HAS_RMM 0
#endif

#if defined(__CUDACC__) && RT_ACE_HAS_CONTEXT && RT_ACE_HAS_EVALUATOR && \
    RT_ACE_HAS_CIPHERTEXT && RT_ACE_HAS_PLAINTEXT && RT_ACE_HAS_RMM
#include <ace/he_engine/Ciphertext.h>
#include <ace/he_engine/Context.h>
#include <ace/he_engine/Evaluator.h>
#include <ace/he_engine/Plaintext.h>
#else
#include <cstdint>

// NOLINTBEGIN (readability-identifier-naming)
namespace acelib {
namespace host {
using parms_id_type = std::uint64_t;
}

class DeviceCipher {};
class DevicePlain {};
}  // namespace acelib

// NOLINTEND (readability-identifier-naming)
#endif

#undef RT_ACE_HAS_CONTEXT
#undef RT_ACE_HAS_EVALUATOR
#undef RT_ACE_HAS_CIPHERTEXT
#undef RT_ACE_HAS_PLAINTEXT
#undef RT_ACE_HAS_RMM

#include "common/tensor.h"
#include "rt_def.h"

typedef double SCALE_T;
typedef acelib::host::parms_id_type LEVEL_T;

// NOLINTBEGIN (readability-identifier-naming)

#ifdef __cplusplus
extern "C" {
#endif

//! @brief Seal API for context management
void AceLibrary_prepare_input(TENSOR* input, const char* name);
void AceLibrary_set_output_data(const char* name, size_t idx, CIPHER data);
CIPHERTEXT AceLibrary_get_input_data(const char* name, size_t idx);
void       AceLibrary_encode_float(PLAIN plain, float* input, size_t len,
                                   SCALE_T scale, LEVEL_T level);
void       AceLibrary_encode_double(PLAIN plain, double* input, size_t len,
                                    SCALE_T scale, LEVEL_T level);
void AceLibrary_encode_float_cst_lvl(PLAIN plain, float* input, size_t len,
                                     SCALE_T scale, int level);
void AceLibrary_encode_float_gpu(PLAIN plain, float* input, size_t len,
                                 SCALE_T scale, int level);
void AceLibrary_encode_double_cst_lvl(PLAIN plain, double* input, size_t len,
                                      SCALE_T scale, int level);
void AceLibrary_encode_float_mask(PLAIN plain, float input, size_t len,
                                  SCALE_T scale, LEVEL_T level);
void AceLibrary_encode_double_mask(PLAIN plain, double input, size_t len,
                                   SCALE_T scale, LEVEL_T level);
void AceLibrary_encode_float_mask_cst_lvl(PLAIN plain, float input, size_t len,
                                          SCALE_T scale, int level);
void AceLibrary_encode_double_mask_cst_lvl(PLAIN plain, double input,
                                           size_t len, SCALE_T scale,
                                           int level);
double* AceLibrary_handle_output(const char* name);

//! @brief Seal API for evaluation
void AceLibrary_add_ciph(CIPHER res, CIPHER op1, CIPHER op2);
void AceLibrary_add_plain(CIPHER res, CIPHER op1, PLAIN op2);
void AceLibrary_add_scalar(CIPHER res, CIPHER op1, double op2);
void AceLibrary_mul_ciph(CIPHER res, CIPHER op1, CIPHER op2);
void AceLibrary_mul_plain(CIPHER res, CIPHER op1, PLAIN op2);
void AceLibrary_mul_scalar(CIPHER res, CIPHER op1, double op2);
void AceLibrary_rotate(CIPHER res, CIPHER op, int step);
void AceLibrary_rescale(CIPHER res, CIPHER op);
void AceLibrary_mod_switch(CIPHER res, CIPHER op);
void AceLibrary_relin(CIPHER res, CIPHER3 op);
void AceLibrary_copy(CIPHER res, CIPHER op);
void AceLibrary_zero(CIPHER res);

void AceLibrary_bootstrap(CIPHER res, CIPHER op, int level);

//! @brief Return whether bts is required
//! generated by fhe-cmplr
bool Need_bts();

SCALE_T AceLibrary_scale_degree(CIPHER res);
SCALE_T AceLibrary_scale(CIPHER res);
LEVEL_T AceLibrary_level(CIPHER res);

#ifdef __cplusplus
}
#endif

// NOLINTEND (readability-identifier-naming)

#endif  // RTLIB_RT_ACE_ACE_API_H
