//-*-c-*-
//=============================================================================
//
// Copyright (c) Ant Group Co., Ltd
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//=============================================================================

#ifndef RTLIB_RT_HYPERFHE_HYPERFHE_API_H
#define RTLIB_RT_HYPERFHE_HYPERFHE_API_H

//! @brief hyperfhe_api.h
//! Define hyperfhe API can be used by rtlib

// #include <seal/seal.h>
// #include "seal/seal.h"
#include "Context.h"
#include "Evaluator.h"
#include "Ciphertext.h"

#include "common/tensor.h"
#include "rt_def.h"

typedef double              SCALE_T;
typedef frontend::parms_id_type LEVEL_T;

#ifdef __cplusplus
extern "C" {
#endif

//! @brief Seal API for context management
void       Hyperfhe_prepare_input(TENSOR* input, const char* name);
void       Hyperfhe_set_output_data(const char* name, size_t idx, CIPHER data);
CIPHERTEXT Hyperfhe_get_input_data(const char* name, size_t idx);
void Hyperfhe_encode_float(PLAIN plain, float* input, size_t len, SCALE_T scale,
                       LEVEL_T level);
void Hyperfhe_encode_double(PLAIN plain, double* input, size_t len, SCALE_T scale,
                        LEVEL_T level);
void Hyperfhe_encode_float_cst_lvl(PLAIN plain, float* input, size_t len,
                               SCALE_T scale, int level);
void Hyperfhe_encode_double_cst_lvl(PLAIN plain, double* input, size_t len,
                                SCALE_T scale, int level);
void Hyperfhe_encode_float_mask(PLAIN plain, float input, size_t len, SCALE_T scale,
                            LEVEL_T level);
void Hyperfhe_encode_double_mask(PLAIN plain, double input, size_t len,
                             SCALE_T scale, LEVEL_T level);
void Hyperfhe_encode_float_mask_cst_lvl(PLAIN plain, float input, size_t len,
                                    SCALE_T scale, int level);
void Hyperfhe_encode_double_mask_cst_lvl(PLAIN plain, double input, size_t len,
                                     SCALE_T scale, int level);
double* Hyperfhe_handle_output(const char* name);

//! @brief Seal API for evaluation
void Hyperfhe_add_ciph(CIPHER res, CIPHER op1, CIPHER op2);
void Hyperfhe_add_plain(CIPHER res, CIPHER op1, PLAIN op2);
void Hyperfhe_add_scalar(CIPHER res, CIPHER op1, double op2);
void Hyperfhe_mul_ciph(CIPHER res, CIPHER op1, CIPHER op2);
void Hyperfhe_mul_plain(CIPHER res, CIPHER op1, PLAIN op2);
void Hyperfhe_mul_scalar(CIPHER res, CIPHER op1, double op2);
void Hyperfhe_rotate(CIPHER res, CIPHER op, int step);
void Hyperfhe_rescale(CIPHER res, CIPHER op);
void Hyperfhe_mod_switch(CIPHER res, CIPHER op);
void Hyperfhe_relin(CIPHER res, CIPHER3 op);
void Hyperfhe_copy(CIPHER res, CIPHER op);
void Hyperfhe_zero(CIPHER res);

void Hyperfhe_bootstrap(CIPHER res, CIPHER op, int level);

//! @brief Return whether bts is required
//! generated by fhe-cmplr
bool Need_bts();

SCALE_T Hyperfhe_scale_degree(CIPHER res);
SCALE_T Hyperfhe_scale(CIPHER res);
LEVEL_T Hyperfhe_level(CIPHER res);

#ifdef __cplusplus
}
#endif

#endif  // RTLIB_RT_SEAL_SEAL_API_H

