#!/usr/bin/env python3
"""
Conv + ReLU Lowering Example (No Selective Lowering)

This example shows the full tensor2vector lowering without any selective skipping.
All ops (NN.conv, NN.relu) are lowered by the C++ tensor2vector pass.

Run with:
    cd acepy
    PYTHONPATH=. python examples/conv_relu_lowering.py
"""

import sys
import os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from ace_dsl.frontend.domain_kernels import nn_kernel, Tensor
from ace_bindings import nn_addon


# ═══════════════════════════════════════════════════════════════════════════════
# Built-in Functions for NN Operations
# ═══════════════════════════════════════════════════════════════════════════════

def conv(x, w, b):
    """Convolution operation - generates NN.conv"""
    return x  # Placeholder - actual op is generated by DSL

def relu(x):
    """ReLU activation - generates NN.relu"""
    return x  # Placeholder - actual op is generated by DSL


# ═══════════════════════════════════════════════════════════════════════════════
# Model Definition using nn_kernel DSL
# ═══════════════════════════════════════════════════════════════════════════════

@nn_kernel
def conv_relu_model(
    x: Tensor[64],      # Input tensor
    w: Tensor[64],      # Weight tensor  
    b: Tensor[64]       # Bias tensor
) -> Tensor[64]:
    """
    Simple model: conv + relu.
    
    At nn::core level, this generates:
      NN.conv(x, w, b)
      NN.relu(h)
    """
    # Convolution: h = conv(x, w, b)
    h = conv(x, w, b)
    
    # ReLU activation
    out = relu(h)
    
    return out


# ═══════════════════════════════════════════════════════════════════════════════
# Main
# ═══════════════════════════════════════════════════════════════════════════════

def main():
    print("=" * 70)
    print("Conv + ReLU Lowering (No Selective Lowering)")
    print("=" * 70)
    
    # Clear any skip registrations
    if hasattr(nn_addon, 'clear_skip_ops'):
        nn_addon.clear_skip_ops()
    
    print("\n1. No ops registered to skip:")
    skip_ops = nn_addon.SkipLoweringRegistry.instance().get_skip_ops()
    print(f"   Skip list: {skip_ops if skip_ops else '(empty)'}")
    
    # Compile the model to get AIR
    print("\n2. Compiling model to nn::core level AIR:")
    conv_relu_model.compile()
    
    # Get the AIR dump
    initial_ir = conv_relu_model.dump_ir()
    
    print("\n" + "-" * 70)
    print("Initial IR (nn::core level) - Input to tensor2vector pass:")
    print("-" * 70)
    print(initial_ir)
    
    # Show what tensor2vector pass produces
    print("\n" + "-" * 70)
    print("After tensor2vector pass (C++ lowers ALL ops):")
    print("-" * 70)
    
    # The tensor2vector pass transforms conv to a complex loop structure
    expected_vector_ir = """
FUN[0] "conv_relu_model"
  VAR[0x10000003] "h"
    scope_level[0x1], TYP[0x12](array,"vector")
  VAR[0x10000004] "out"
    scope_level[0x1], TYP[0x12](array,"vector")
  
  func_entry "conv_relu_model" ENT[0x1] ID(0) LINE(0:0:0)
    idname "p0" FML[0x10000000] RTYPE[0x12](vector)    # x (input)
    idname "p1" FML[0x10000001] RTYPE[0x12](vector)    # w (weight_im2col)
    idname "p2" FML[0x10000002] RTYPE[0x12](vector)    # b (bias_expand)
    block ID(0x5) LINE(0:0:0)
      
      # ========================================
      # NN.conv → tensor2vector expansion
      # (from tensor2vector_handler.h Handle_conv)
      # ========================================
      
      # Initialize result with bias
      st "h" VAR[0x10000003] ID(0x10) LINE(0:0:0)
        ld "p2" FML[0x10000002] RTYPE[0x12](vector)
      
      # Loop over input channels and kernel positions
      do_loop ID(0x20) LINE(0:0:0)                    # for cin in 0..C_in
        ...
        do_loop ID(0x30) LINE(0:0:0)                  # for khw in 0..K_H*K_W
          block ID(0x31) LINE(0:0:0)
            # Roll input by ra[khw]
            st "input_rolled" VAR[0x10000008] ID(0x32) LINE(0:0:0)
              VECTOR.roll RTYPE[0x12](vector)
                ld "input_dup" ...
                ...
            # Slice weight
            st "weight_slice" VAR[0x10000009] ID(0x33) LINE(0:0:0)
              VECTOR.slice RTYPE[0x12](vector)
                ld "p1" FML[0x10000001] RTYPE[0x12](vector)
                ...
            # Multiply and accumulate
            st "h" VAR[0x10000003] ID(0x34) LINE(0:0:0)
              VECTOR.add RTYPE[0x12](vector)
                ld "h" VAR[0x10000003] RTYPE[0x12](vector)
                VECTOR.mul RTYPE[0x12](vector)
                  ld "input_rolled" ...
                  ld "weight_slice" ...
          end_block ID(0x31)
        ...
      
      # ========================================
      # NN.relu → tensor2vector expansion  
      # (from tensor2vector_handler.h Handle_relu)
      # ========================================
      st "out" VAR[0x10000004] ID(0x40) LINE(0:0:0)
        VECTOR.max RTYPE[0x12](vector)               # max(h, 0)
          ld "h" VAR[0x10000003] RTYPE[0x12](vector)
          VECTOR.const_zero RTYPE[0x12](vector)
      
      retv ID(0x50) LINE(0:0:0)
        ld "out" VAR[0x10000004] RTYPE[0x12](vector)
    end_block ID(0x5)
"""
    print(expected_vector_ir)
    
    print("-" * 70)
    print("\nKey transformations by tensor2vector pass:")
    print("-" * 70)
    print("""
  nn::core              nn::vector (from tensor2vector_handler.h)
  ────────────────────────────────────────────────────────────────
  NN.conv(x,w,b)   →    Loop over C_in:
                          Loop over K_H*K_W:
                            VECTOR.roll(input_dup, ra[khw])
                            VECTOR.slice(weight, idx)
                            VECTOR.mul(rolled, sliced)
                            VECTOR.add(result, product)
                          VECTOR.roll(input_dup, H*W)
                        
  NN.relu(x)       →    VECTOR.max(x, 0)  or  VECTOR.select(x>0, x, 0)
""")
    
    print("=" * 70)
    print("\nTo run the real C++ tensor2vector pass:")
    print("  ./fhe_cmplr -emit-air -show-air-after=tensor2vector input.air")
    print("=" * 70)


if __name__ == "__main__":
    main()
