//-*-c-*-
//=============================================================================
//
// Copyright (c) Ant Group Co., Ltd
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//=============================================================================

#ifndef RTLIB_RT_ACE_LIBRARY_ACE_LIBRARY_API_H
#define RTLIB_RT_ACE_LIBRARY_ACE_LIBRARY_API_H

//! @brief ace_library_api.h
//! Define ace_library API can be used by rtlib.
//! Always includes the real SDK headers — both libFHErt_ace.so and
//! the generated kernel .cu are compiled with the SDK include paths,
//! so cuckks::DeviceCipher / DevicePlain are the real types everywhere.

#include "Ciphertext.h"
#include "Context.h"
#include "Evaluator.h"
#include "Plaintext.h"

#include "common/tensor.h"
#include "rt_def.h"

typedef double SCALE_T;
typedef size_t  LEVEL_T;

// NOLINTBEGIN (readability-identifier-naming)

#ifdef __cplusplus
extern "C" {
#endif

//! @brief Seal API for context management
void AceLibrary_prepare_input(TENSOR* input, const char* name);
void AceLibrary_set_output_data(const char* name, size_t idx, CIPHER data);
void       AceLibrary_encode_float(PLAIN plain, float* input, size_t len,
                                   SCALE_T scale, LEVEL_T level);
void       AceLibrary_encode_double(PLAIN plain, double* input, size_t len,
                                    SCALE_T scale, LEVEL_T level);
void AceLibrary_encode_float_cst_lvl(PLAIN plain, float* input, size_t len,
                                     SCALE_T scale, int level);
void AceLibrary_encode_float_gpu(PLAIN plain, float* input, size_t len,
                                 SCALE_T scale, int level);
void AceLibrary_encode_double_cst_lvl(PLAIN plain, double* input, size_t len,
                                      SCALE_T scale, int level);
void AceLibrary_encode_float_mask(PLAIN plain, float input, size_t len,
                                  SCALE_T scale, LEVEL_T level);
void AceLibrary_encode_double_mask(PLAIN plain, double input, size_t len,
                                   SCALE_T scale, LEVEL_T level);
void AceLibrary_encode_float_mask_cst_lvl(PLAIN plain, float input, size_t len,
                                          SCALE_T scale, int level);
void AceLibrary_encode_double_mask_cst_lvl(PLAIN plain, double input,
                                           size_t len, SCALE_T scale,
                                           int level);
double* AceLibrary_handle_output(const char* name);

//! @brief Seal API for evaluation
void AceLibrary_add_ciph(CIPHER res, CIPHER op1, CIPHER op2);
void AceLibrary_add_plain(CIPHER res, CIPHER op1, PLAIN op2);
void AceLibrary_add_scalar(CIPHER res, CIPHER op1, double op2);
void AceLibrary_mul_ciph(CIPHER res, CIPHER op1, CIPHER op2);
void AceLibrary_mul_plain(CIPHER res, CIPHER op1, PLAIN op2);
void AceLibrary_mul_scalar(CIPHER res, CIPHER op1, double op2);
void AceLibrary_rotate(CIPHER res, CIPHER op, int step);
void AceLibrary_rescale(CIPHER res, CIPHER op);
void AceLibrary_mod_switch(CIPHER res, CIPHER op);
void AceLibrary_relin(CIPHER res, CIPHER3 op);
void AceLibrary_copy(CIPHER res, CIPHER op);
void AceLibrary_zero(CIPHER res);

void AceLibrary_bootstrap(CIPHER res, CIPHER op, int level);

//! @brief Return whether bts is required
//! generated by fhe-cmplr
bool Need_bts();

SCALE_T AceLibrary_scale_degree(CIPHER res);
SCALE_T AceLibrary_scale(CIPHER res);
LEVEL_T AceLibrary_level(CIPHER res);

#ifdef __cplusplus
}
#endif

//! @brief Return an input ciphertext by name and index.
//! The caller receives ownership of the returned value (move semantics).
CIPHERTEXT AceLibrary_get_input_data(const char* name, size_t idx);

// NOLINTEND (readability-identifier-naming)

#endif  // RTLIB_RT_ACE_LIBRARY_ACE_LIBRARY_API_H